/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dnd.gooding.openapi.apis;

import com.dnd.gooding.openapi.models.Error;
import com.dnd.gooding.openapi.models.SubscriptionOrdersModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "order", description = "the order API")
public interface OrderApi {

    /**
     * GET /apis/orders : 특정 유저의 모든 주문내역을 조회합니다.
     *
     * @param v The version of api (optional)
     * @param user user name (optional)
     * @param detail user detail (optional)
     * @return 모든 주문 내역을 반환 합니다. (status code 200)
     *         or unexpected error (status code 400)
     */
    @Operation(
        operationId = "showAllOrdersByUsers",
        summary = "특정 유저의 모든 주문내역을 조회합니다.",
        tags = { "order" },
        responses = {
            @ApiResponse(responseCode = "200", description = "모든 주문 내역을 반환 합니다.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SubscriptionOrdersModel.class)))
            }),
            @ApiResponse(responseCode = "400", description = "unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/apis/orders",
        produces = { "application/json" }
    )
    ResponseEntity<List<SubscriptionOrdersModel>> showAllOrdersByUsers(
        @Parameter(name = "v", description = "The version of api", in = ParameterIn.QUERY) @Valid @RequestParam(value = "v", required = false) String v,
        @Parameter(name = "user", description = "user name", in = ParameterIn.QUERY) @Valid @RequestParam(value = "user", required = false) String user,
        @Parameter(name = "detail", description = "user detail", in = ParameterIn.QUERY) @Valid @RequestParam(value = "detail", required = false) String detail
    );

}
